### ISSUE TITLE
Fly out menu example on WAI tutorials seems to use aria-haspopup which may not be optimal

### ISSUE THREAD

**Issue by mraccess77** [w3c/wai-tutorials#624] opened 2021-02-02 17:22 UTC
The flyout controls page indicates haspopup should be used to indicate menus - but this structure is not a menu.  Also in ARIA 1.2 haspopup is being deprecated as a global attribute and will only be usable on certain controls.  I would recommend the pattern be updated to follow the ARIA authoring practices example:
Current Flyout:
https://www.w3.org/WAI/tutorials/menus/flyout/
Recommended ARIA practices approach:
https://w3c.github.io/aria-practices/examples/disclosure/disclosure-navigation.html

**Comment by JAWS-test** [comment] 2021-02-03 04:55
I think it is sufficient to remove the aria-haspopup. The rest of the example can stay as it is. The use of links instead of buttons makes more sense in a navigation

**Comment by yatil** [comment] 2021-02-09 12:53
Version 2.0 of the page (integrating it into the current WAI design and fixing the most outrageous bugs), which was completed over 11 months ago, also still has aria-haspopup: https://wai-tutorials.netlify.app/tutorials/menus/flyout/

I agree that it can be completely removed.

**Comment by yatil** [comment] 2021-02-09 13:00
Duplicate of #611.

**Comment by brianelton** [comment] 2022-09-02 18:03
aria-haspopup removed in PR #633

**Closed by brianelton** 2022-09-02 18:03 UTC
