### ISSUE TITLE
Application Menu Example & Code -- Keyboard Tabbing

### ISSUE THREAD

**Issue by devarshipant** [w3c/wai-tutorials#544] opened 2017-09-05 17:31 UTC
https://www.w3.org/WAI/tutorials/menus/application-menus-code/

Note the errant interaction (IE 11) where tabbing locks the keyboard focus within the menu. Arrow keys work as expected, but tabbing does not. Tabbing should let the user go past the menu.

**Comment by yatil** [comment] 2018-08-23 12:28
Duplicate of #552 (which came later and had other things to address, too) and fixed in #563.

**Closed by yatil** 2018-08-23 12:28 UTC
