### ISSUE TITLE
carousel keyboard focus after using prev / next button and name of those buttons

### ISSUE THREAD

**Issue by goetsu** [w3c/wai-tutorials#385] opened 2016-12-27 17:07 UTC
Hi,

the current example is an infinite carousel that have button to go to prev / next slide. My concern is that when user is on the last  slide  the name of the next buttons doesn't change so the user doesn't know he was going back the the first. 
possible solutions : 
* remove infinite mode by  adding an aria-disabled="true" attribut to the next slide button on last slide and prev slide button on first slide and remove onclick event handler 
* change alt of the img of the next slide button on last slide and of the img of prev slide button on first slide to something like "go to first slide" / "go to last slide"

Another problem is that when user activate prev / next button I think that focus must be moved on the slide and not stay on the button as it's the case with the navigation links

**Comment by yatil** [comment] 2016-12-28 13:53
Hi @goetsu, I will look into providing the information when the carousel starting to repeat.

The focus not moving to the slide is deliberate to allow skipping through several slides quickly, especially for people who use screens and the keyboard, this is probably the expected behavior. (This aspect hopefully gets more clear in the current rewrite that I’m doing.)

Thanks for your feedback!

**Comment by yatil** [comment] 2017-01-05 13:42
Hi @goetsu, just having another look – we actually use a aria-live region that announces the current slide – even if the focused is not moved. I think this is sufficient for now. Feel free to reopen this issue if you don’t agree.

**Comment by yatil** [comment] 2017-01-05 14:19
(But I might want to make that much more clear.)

**Comment by goetsu** [comment] 2017-01-05 14:50
@yatil no aria-live at the moment on that example also, and I a say a very bad idea due to the autoplay feature

**Comment by goetsu** [comment] 2017-01-06 08:51
@yatil sadly this solution doesn't work on Voiceover osX and with NVDA, only word with jaws 17 and FF (not IE 11).
The only possible solution I see in that case is to add the aria-live attribut not of activation of the next / prev button but when focus is inside the carrousel and remove it when focus go out off the carrousel

**Comment by yatil** [comment] 2017-01-06 09:19
I have a hard time parsing your second sentence there.

The demo worked for me, but I have just rolled out an update (to the working demo only for now) that announces only the heading (which makes it more brief). It works with VoiceOver, see this video: https://www.dropbox.com/s/0nmgwm8lowyabqi/carousel-voiceover-macos.mp4?dl=0

I also added aria-atomic=true to ensure that the full headline is read.

**Comment by goetsu** [comment] 2017-01-06 14:42
Ok I  update to sierra and it's working now (but still not with nvda), I think it announce 4 because it's a h4

**Comment by yatil** [comment] 2017-01-06 14:45
Hm, that makes sense. I’ll have another look with NVDA.

**Comment by yatil** [comment] 2017-01-06 16:40
Reopened as it is quite severe in NVDA – at least as far as I can see. Thanks for bringing it up @goetsu, I will change the implementation.

**Comment by goetsu** [comment] 2017-01-06 16:47
maybe with the previous solution I give is an idea : add the aria-live attribut not of activation of the next / prev button but when focus is inside the carrousel and remove it when focus go out of the carousel

**Comment by yatil** [comment] 2017-01-06 16:50
Yeah. That would be an idea. Another is to just add the title of the next slide to the previous/next buttons and not bother with ARIA-live at all.

Or have a live region div hidden from view and write the name in there using JavaScript. Adding the ARIA-live attribute seems to be not enough to trigger the speech output.

**Comment by peasandwell** [comment] 2017-01-16 14:53
Hi, relating to ARIA-live, I've been experimenting with your carousel and it seems that with NVDA & IE11 the slides are announced when navigating, but not in Firefox at all.

Is the NVDA & FF combination known to have issues with ARIA-live and ARIA-hidden?

**Comment by yatil** [comment] 2017-01-16 16:51
@peasandwell – Did you try the editor’s draft version on GitHub.io? It should work fine. The aria-live region is not involved with aria-hidden as they affect different portions of the code.

**Comment by peasandwell** [comment] 2017-01-17 11:04
@yatil just had a look at it, works great for both browsers. I considered using a similar approach but I was a bit unsure whether having a loose bit of text would be weird, but your example has convinced me! Thanks!

**Closed** 2017-01-18 08:08 UTC
Labels: Carousels Tutorial
