### ISSUE TITLE
add link to web accessibility perspectives as resource on tutorials main page

### ISSUE THREAD

**Issue by nrhsinclair** [w3c/wai-tutorials#541] opened 2017-08-03 19:38 UTC
On the Tutorials home page http://wai.accessibility.rocks/aria-concepts/build/
under Additional Resources section, would suggest adding link to the Web Accessibility Perspectives Videos https://www.w3.org/WAI/perspectives/ It is such a great resource that may otherwise be difficult to find.

**Comment by yatil** [comment] 2017-08-04 09:18
I like the idea.

**Comment by nitedog** [comment] 2017-08-04 14:03
I recall previous comments on confusion caused by overly cross-linking resources, especially for people who are newer and less oriented, and get lost in circular links. Aren't resources going to be easier to find and to navigate with the new site design? We should be careful, as I think Perspectives is good to link from nearly any WAI resource (yes, I'm a little biased).

**Comment by yatil** [comment] 2017-08-04 19:40
I see @nitedog’s point. And we might have the perspectives linked from the front page as well. I don’t think we have immediate updates to the tutorials but let’s reevaluate after the new design goes live.

**Comment by VivienneConway** [comment] 2017-08-09 05:35
I agree that we need to be careful.  While the Perspectives videos are useful link from all of the pages, it will clutter things if we have too many cross-references.  Under that Additional Resources, when you follow it you come to the resource of how people with disabilities use the web, and it could obviously have a link there too.  Can we somehow have all resources listed and just point to a list?  Sorry, may that is already being done.

**Comment by yatil** [comment] 2017-08-09 06:44
Let’s put the discussion on hold until we have relaunched and see how it shakes out.

**Comment by brianelton** [comment] 2022-09-02 18:35
So, almost 4 years on and a new design implemented (perhaps the second new design) I would say that the additional link is not necessary. The "How People with Disabilities Use the Web" link takes the user to the same section of the site as the Perspective videos, and they are easily reachable from there. Also, the "How People with Disabilities Use the Web" section is getting new content soon, which will complement the Perspective videos very well.

https://www.w3.org/WAI/tutorials/

**Comment by brianelton** [comment] 2023-05-09 21:06
Discussed with @shawna-slh and @lakeen. To lower the cross linking and keep the focus on the How People with disabilities use the web section. The new tutorials site is integrated with the rest of the WAI site and all of these resources are easily found.
Closing.

**Closed by brianelton** 2023-05-09 21:06 UTC
Labels: content
