### ISSUE TITLE
Help improve this page - leads to github 404 page

### ISSUE THREAD

**Issue by hans2103** [w3c/wai-tutorials#645] opened 2022-03-11 13:14 UTC
At the bottom of https://www.w3.org/WAI/tutorials/menus/flyout/#flyoutnavmousefixed I see the buttom _Fork & Edit on GitHub_
The URL behind this anchor is https://github.com/w3c/wai-tutorials/edit/master/content/menus/flyout.md

This url seems not to exist.
Perhaps it should be changed to https://github.com/w3c/wai-tutorials/edit/master-2.0/content/menus/flyout.md

**Comment by yatil** [comment] 2022-03-11 17:26
I’m about to fix this, WAI just changed the system and this broke :-) also duplicate of #642

**Closed as completed** 2022-03-11 18:25 UTC
